services: 
  - docker
script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -f Dockerfile.local -t cruizba/markdown-to-latex-book
  - docker push cruizba/markdown-to-latex-book
  - docker build -f Dockerfile -t cruizba/gitpod-tfg-crecorder
  - docker push cruizba/gitpod-tfg-crecorder
