services: 
  - docker
script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build . -t cruizba/markdown-to-latex-book
  - docker push cruizba/markdown-to-latex-book